### ISSUE TITLE
FingerprintJS.framework: No such file or directory

### ISSUE THREAD

**Issue by priyanka-vithani** [fingerprintjs/fingerprintjs-ios#45] opened 2023-10-01 21:09 UTC
When I run the project I am getting this error 

I just installed pod and in Appdelegate file I have written below code
 let fingerprinter = FingerprinterFactory.getInstance()
        async {
            // Get fingerprint for the current device
            let fingerprint = await fingerprinter.getDeviceId()
            print(fingerprint)
            
            // Do something awesome with the fingerprint
        }
        
        Please suggest  me some solution for this issue

**Comment by mgutski** [comment] 2023-10-16 12:50
Hi @priyanka-vithani, sorry for the delayed response. I was unable to reproduce your issue on my machine, but I suspect that the above error could be due to the outdated CocoaPods version that is not fully compatible with the latest Xcode. Assuming that you are running Xcode 15.0 (15A240d), you should be using CocoaPods `1.13.0` (current latest) that includes bug fixes for Xcode 15. CocoaPods was always kind of flaky with the new Xcode releases, so updating it might resolve your issue. Please let me know if it helped 🙂

**Comment by mgutski** [comment] 2024-01-17 10:47
Closing as there are no further comments or questions from the issue's author.

**Closed by mgutski** 2024-01-17 10:47 UTC
